/**
 * Locale pt-BR para os componentes do PrimeVue.
 * Referência de chaves: https://primevue.org/configuration/#locale
 */
export const primeVuePtBr = {
    accept: 'Sim',
    reject: 'Não',
    choose: 'Escolher',
    upload: 'Enviar',
    cancel: 'Cancelar',
    clear: 'Limpar',
    apply: 'Aplicar',
    close: 'Fechar',
    completed: 'Concluído',
    pending: 'Pendente',
    emptyMessage: 'Nenhum resultado encontrado',
    emptySearchMessage: 'Nenhum resultado encontrado',
    emptySelectionMessage: 'Nenhum item selecionado',
    emptyFilterMessage: 'Nenhum resultado encontrado',
    dayNames: [
        'Domingo',
        'Segunda',
        'Terça',
        'Quarta',
        'Quinta',
        'Sexta',
        'Sábado',
    ],
    dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
    dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
    monthNames: [
        'Janeiro',
        'Fevereiro',
        'Março',
        'Abril',
        'Maio',
        'Junho',
        'Julho',
        'Agosto',
        'Setembro',
        'Outubro',
        'Novembro',
        'Dezembro',
    ],
    monthNamesShort: [
        'Jan',
        'Fev',
        'Mar',
        'Abr',
        'Mai',
        'Jun',
        'Jul',
        'Ago',
        'Set',
        'Out',
        'Nov',
        'Dez',
    ],
    today: 'Hoje',
    weekHeader: 'Sem',
    firstDayOfWeek: 0,
    dateFormat: 'dd/mm/yy',
    weak: 'Fraca',
    medium: 'Média',
    strong: 'Forte',
    passwordPrompt: 'Digite uma senha',
    searchMessage: '{0} resultados disponíveis',
    selectionMessage: '{0} itens selecionados',
    aria: {
        trueLabel: 'Verdadeiro',
        falseLabel: 'Falso',
        nullLabel: 'Não selecionado',
        pageLabel: 'Página {page}',
        firstPageLabel: 'Primeira página',
        lastPageLabel: 'Última página',
        nextPageLabel: 'Próxima página',
        previousPageLabel: 'Página anterior',
    },
};
